services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Europe/Kyiv

    ports:
      - '${POSTGRES_DOCKER_PORT}:5432'
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - carsharing-network

  app:
    image: carsharing
    build: .
    container_name: carsharing
    depends_on:
      - postgres

    environment:
      TZ: Europe/Kyiv
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Europe/Kyiv"

    ports:
      - '${APP_LOCAL_PORT}:${APP_DOCKER_PORT}'

    env_file:
      - .env
    networks:
      - carsharing-network

volumes:
  postgresql_data:

networks:
  carsharing-network:
    driver: bridge
